version: "3"

services:
  api:
    build: ./backend
    working_dir: /app/back
    volumes:
      - ./backend:/app/back
    container_name: blitz_ebytr_api
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - 3031:3031
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
  frontend:
    build: ./frontend
    container_name: 'blitz_ebytr_frontend'
    ports:
      - 3000:3000
    command: npm start
  db:
    container_name: blitz_ebytr_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: blitz_ebytr_net 